/*
 * This source file was generated by the Gradle 'init' task
 */
package pdfix.java.gradle;

import net.pdfix.pdfixlib.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        try {
        Pdfix pdfix = new Pdfix();
        System.out.println("PDFix SDK " + pdfix.GetVersionMajor() + "." +
                pdfix.GetVersionMinor() + "." + pdfix.GetVersionPatch());
        } catch (Exception ex) {
            System.out.print(ex.getMessage());
        }
    }
}
